version: '3.5'
services:
  db:
    image: postgres:11.2
    container_name: postgres_11_2
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./shared_data/db_data:/var/lib/postgresql/data
    networks:
      - service_network
  orders_api:
    container_name: orders_api
    image: begin29/orders_api_task
    env_file:
      - ./.env
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
      - payments_api
    networks:
      - service_network
  payments_api:
    container_name: payments_api
    image: begin29/payments_api_task
    expose:
      - "3000"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
    name: service_network
